# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Projecy CI/CD flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
#        cache: maven
#    - name: Fetching All
#      run: |
#        git fetch --prune --unshallow
#        # Install Git Version
#    - name: Installing GitVersion
#      uses: gittools/actions/gitversion/setup@v0.9.5
#      with:
#        versionSpec: '5.x'
#        # Use Git Version to compute version of the project
#    - name: Use GitVersion
#      id: gitversion
#      uses: gittools/actions/gitversion/execute@v0.9.5
#    - name: Bump Version
#      uses: 'mickem/gh-action-bump-maven-version'
#      with:
#        bump-command: mvn org.codehaus.mojo:versions-maven-plugin:2.7:set-property -Dproperty=revision -DnewVersion=$NEW_VERSION

        # For a maven artifact, set version to what was computed by GitVersion in earlier step
#    - name: Evaluate New Artifact Version
#      run: |
#        NEW_VERSION=${{ steps.gitversion.outputs.semVer }}
#        echo "Artifact Semantic Version: $NEW_VERSION"
#        mvn versions:set -DnewVersion=${NEW_VERSION}-SNAPSHOT -s pom.xml

    - name: Build with Maven
      run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: shubham710/springboot-image-new
        tags: ${{ github.event.release.tag_name }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


#    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
